spring:
  datasource:
    url: jdbc:h2:file:./target/capvault-local;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

capvault:
  storage:
    provider: local
    local-root: target/capvault-storage
